spring:
  profiles:
    active: prod
  application:
    name: sales_pt_batch
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: never

logging:
  level:
    org:
      springframework:
        batch: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    com:
      zaxxer:
        hikari: DEBUG